// ─── Realistic seed data for Kaiser AI mock mode ───────────────────────────

export const MUMBAI_WARDS = [
  { id: 1,  name: 'A Ward',  area: 'Colaba, Cuffe Parade',       lat: 18.9067, lng: 72.8280 },
  { id: 2,  name: 'B Ward',  area: 'Dongri, Mandvi',             lat: 18.9591, lng: 72.8341 },
  { id: 3,  name: 'C Ward',  area: 'Girgaon, Bhuleshwar',        lat: 18.9528, lng: 72.8223 },
  { id: 4,  name: 'D Ward',  area: 'Malabar Hill, Grant Road',   lat: 18.9573, lng: 72.7983 },
  { id: 5,  name: 'E Ward',  area: 'Byculla, Mazgaon',           lat: 18.9752, lng: 72.8367 },
  { id: 6,  name: 'F/N Ward',area: 'Kurla (North)',               lat: 19.0700, lng: 72.8787 },
  { id: 7,  name: 'F/S Ward',area: 'Dharavi, Sion',               lat: 19.0419, lng: 72.8551 },
  { id: 8,  name: 'G/N Ward',area: 'Bandra (North)',              lat: 19.0596, lng: 72.8296 },
  { id: 9,  name: 'G/S Ward',area: 'Bandra (South)',              lat: 19.0524, lng: 72.8258 },
  { id: 10, name: 'H/E Ward',area: 'Santacruz (East)',            lat: 19.0820, lng: 72.8512 },
  { id: 11, name: 'H/W Ward',area: 'Santacruz (West), Vile Parle', lat: 19.0987, lng: 72.8440 },
  { id: 12, name: 'K/E Ward',area: 'Andheri (East)',              lat: 19.1152, lng: 72.8680 },
  { id: 13, name: 'K/W Ward',area: 'Andheri (West)',              lat: 19.1197, lng: 72.8290 },
  { id: 14, name: 'L Ward',  area: 'Kurla, Sakinaka',            lat: 19.0726, lng: 72.8849 },
  { id: 15, name: 'M/E Ward',area: 'Govandi, Mankhurd',           lat: 19.0426, lng: 72.9159 },
  { id: 16, name: 'M/W Ward',area: 'Chembur (West)',              lat: 19.0538, lng: 72.8990 },
  { id: 17, name: 'N Ward',  area: 'Ghatkopar',                  lat: 19.0868, lng: 72.9083 },
  { id: 18, name: 'P/N Ward',area: 'Goregaon (North)',            lat: 19.1617, lng: 72.8492 },
  { id: 19, name: 'P/S Ward',area: 'Goregaon (South), Jogeshwari', lat: 19.1392, lng: 72.8499 },
  { id: 20, name: 'R/C Ward',area: 'Kandivali (East)',            lat: 19.2064, lng: 72.8554 },
  { id: 21, name: 'R/N Ward',area: 'Dahisar',                    lat: 19.2372, lng: 72.8522 },
  { id: 22, name: 'R/S Ward',area: 'Kandivali (West), Borivali (South)', lat: 19.2115, lng: 72.8383 },
  { id: 23, name: 'S Ward',  area: 'Mulund',                     lat: 19.1728, lng: 72.9564 },
  { id: 24, name: 'T Ward',  area: 'Bhandup, Nahur',             lat: 19.1449, lng: 72.9382 },
  { id: 25, name: 'RC Ward', area: 'Borivali (East)',             lat: 19.2292, lng: 72.8660 },
  { id: 26, name: 'RS Ward', area: 'Malad',                      lat: 19.1875, lng: 72.8448 },
];

export const CATEGORIES = [
  'Pothole',
  'Garbage',
  'Drainage',
  'Streetlight',
  'Water Leakage',
  'Other',
];

export const COMPLAINT_STATUSES = ['reported', 'assigned', 'in_progress', 'resolved', 'duplicate'];

export const MOCK_USERS = {
  citizen: {
    id: 'user-001',
    name: 'Priya Nair',
    email: 'priya.nair@example.com',
    phone: '+91 98765 43210',
    role: 'citizen',
    ward: 8,
    wardName: 'G/N Ward – Bandra (North)',
    avatarInitials: 'PN',
    createdAt: '2024-03-15T10:30:00Z',
  },
  officer: {
    id: 'officer-001',
    name: 'Suresh Patil',
    email: 'suresh.patil@bmc.gov.in',
    phone: '+91 22 2416 6000',
    role: 'officer',
    ward: 12,
    wardName: 'K/E Ward – Andheri (East)',
    department: 'Roads & Infrastructure',
    employeeId: 'BMC/KE/2021/047',
    avatarInitials: 'SP',
    createdAt: '2021-07-01T09:00:00Z',
  },
  admin: {
    id: 'admin-001',
    name: 'Rajendra Mehta',
    email: 'r.mehta@bmc.gov.in',
    phone: '+91 22 2262 0251',
    role: 'admin',
    department: 'Municipal Commissioner Office',
    avatarInitials: 'RM',
    createdAt: '2020-01-15T08:00:00Z',
  },
};

const makeDateAgo = (days) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

export const MOCK_COMPLAINTS = [
  {
    id: 'cmp-001',
    title: 'Large pothole on SV Road near Bandra station',
    description: 'A 2-foot wide, 6-inch deep pothole has formed on SV Road, 200 meters north of Bandra railway station. Vehicles are swerving dangerously, especially during peak hours and rain.',
    category: 'Pothole',
    severity: 87,
    latitude: 19.0596,
    longitude: 72.8296,
    ward: 8,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    status: 'in_progress',
    createdBy: { id: 'user-001', name: 'Priya Nair' },
    assignedOfficer: { id: 'officer-002', name: 'Amol Desai' },
    upvoteCount: 143,
    commentCount: 18,
    createdAt: makeDateAgo(12),
    resolvedAt: null,
    aiAnalysis: { categoryDetected: 'Pothole', confidence: 0.94, aqiAtLocation: 112, weatherCondition: 'Post-rain' },
  },
  {
    id: 'cmp-002',
    title: 'Overflowing garbage bins at Lokhandwala market',
    description: 'Three municipal garbage bins in Lokhandwala market complex have been overflowing for 4 days. The garbage is spilling onto the road causing odour and health hazard.',
    category: 'Garbage',
    severity: 72,
    latitude: 19.1197,
    longitude: 72.8290,
    ward: 13,
    imageUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&q=80',
    status: 'assigned',
    createdBy: { id: 'user-002', name: 'Arun Shetty' },
    assignedOfficer: { id: 'officer-003', name: 'Kavita Jadhav' },
    upvoteCount: 89,
    commentCount: 7,
    createdAt: makeDateAgo(5),
    resolvedAt: null,
    aiAnalysis: { categoryDetected: 'Garbage', confidence: 0.91, aqiAtLocation: 145, weatherCondition: 'Humid' },
  },
  {
    id: 'cmp-003',
    title: 'Broken streetlight at Dadar TT Circle',
    description: 'Streetlight pole #DT-0042 near Dadar TT Circle is completely dark since 10 days. The area becomes very unsafe at night for pedestrians.',
    category: 'Streetlight',
    severity: 55,
    latitude: 19.0196,
    longitude: 72.8465,
    ward: 7,
    imageUrl: 'https://images.unsplash.com/photo-1518893883800-45cd0954574b?w=600&q=80',
    status: 'resolved',
    createdBy: { id: 'user-003', name: 'Meena Kulkarni' },
    assignedOfficer: { id: 'officer-004', name: 'Rahul Tiwari' },
    upvoteCount: 34,
    commentCount: 5,
    createdAt: makeDateAgo(22),
    resolvedAt: makeDateAgo(8),
    aiAnalysis: { categoryDetected: 'Streetlight', confidence: 0.88, aqiAtLocation: 98, weatherCondition: 'Clear' },
  },
  {
    id: 'cmp-004',
    title: 'Drainage overflow flooding Malad market road',
    description: 'The main storm drain on Malad West market road has been blocked, causing flooding even during light rain. Shopkeepers are reporting water entering premises.',
    category: 'Drainage',
    severity: 91,
    latitude: 19.1875,
    longitude: 72.8448,
    ward: 26,
    imageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=600&q=80',
    status: 'reported',
    createdBy: { id: 'user-004', name: 'Devendra Pawar' },
    assignedOfficer: null,
    upvoteCount: 218,
    commentCount: 32,
    createdAt: makeDateAgo(2),
    resolvedAt: null,
    aiAnalysis: { categoryDetected: 'Drainage', confidence: 0.97, aqiAtLocation: 134, weatherCondition: 'Monsoon' },
  },
  {
    id: 'cmp-005',
    title: 'Water pipeline burst on Linking Road',
    description: 'A water supply pipeline has burst near Linking Road, Khar. Water is gushing out onto the road for 6+ hours. Major water wastage and traffic disruption.',
    category: 'Water Leakage',
    severity: 95,
    latitude: 19.0695,
    longitude: 72.8340,
    ward: 9,
    imageUrl: 'https://images.unsplash.com/photo-1570887830800-53c6e09d99f7?w=600&q=80',
    status: 'in_progress',
    createdBy: { id: 'user-005', name: 'Sangeeta Joshi' },
    assignedOfficer: { id: 'officer-001', name: 'Suresh Patil' },
    upvoteCount: 312,
    commentCount: 41,
    createdAt: makeDateAgo(1),
    resolvedAt: null,
    aiAnalysis: { categoryDetected: 'Water Leakage', confidence: 0.96, aqiAtLocation: 88, weatherCondition: 'Overcast' },
  },
  {
    id: 'cmp-006',
    title: 'Illegal construction debris dumped on footpath',
    description: 'Construction rubble from a building at Borivali East has been dumped on the public footpath near D-Mart, blocking pedestrian movement completely.',
    category: 'Other',
    severity: 48,
    latitude: 19.2292,
    longitude: 72.8660,
    ward: 25,
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&q=80',
    status: 'assigned',
    createdBy: { id: 'user-006', name: 'Pratap Rane' },
    assignedOfficer: { id: 'officer-005', name: 'Sneha Mhatre' },
    upvoteCount: 27,
    commentCount: 3,
    createdAt: makeDateAgo(7),
    resolvedAt: null,
    aiAnalysis: { categoryDetected: 'Other', confidence: 0.79, aqiAtLocation: 105, weatherCondition: 'Clear' },
  },
  {
    id: 'cmp-007',
    title: 'Multiple potholes on Mulund-Airoli road',
    description: 'Stretch of approximately 500 meters on the Mulund-Airoli road has at least 8 significant potholes causing vehicle damage and accidents. Two-wheelers especially at risk.',
    category: 'Pothole',
    severity: 83,
    latitude: 19.1728,
    longitude: 72.9564,
    ward: 23,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    status: 'reported',
    createdBy: { id: 'user-007', name: 'Tushar Naik' },
    assignedOfficer: null,
    upvoteCount: 97,
    commentCount: 14,
    createdAt: makeDateAgo(4),
    resolvedAt: null,
    aiAnalysis: { categoryDetected: 'Pothole', confidence: 0.92, aqiAtLocation: 121, weatherCondition: 'Post-rain' },
  },
  {
    id: 'cmp-008',
    title: 'Garbage pile near Chembur railway station',
    description: 'Uncollected garbage near Chembur station exit for 3 days. The pile is attracting stray dogs and birds. Public hygiene issue.',
    category: 'Garbage',
    severity: 65,
    latitude: 19.0538,
    longitude: 72.8990,
    ward: 16,
    imageUrl: 'https://images.unsplash.com/photo-1604187351574-c75ca79f5807?w=600&q=80',
    status: 'resolved',
    createdBy: { id: 'user-008', name: 'Laxmi Deshmukh' },
    assignedOfficer: { id: 'officer-006', name: 'Vikram Salvi' },
    upvoteCount: 56,
    commentCount: 9,
    createdAt: makeDateAgo(18),
    resolvedAt: makeDateAgo(5),
    aiAnalysis: { categoryDetected: 'Garbage', confidence: 0.89, aqiAtLocation: 118, weatherCondition: 'Sunny' },
  },
];

export const MOCK_OFFICERS = [
  {
    id: 'officer-001',
    name: 'Suresh Patil',
    email: 'suresh.patil@bmc.gov.in',
    phone: '+91 22 2416 6000',
    ward: 12,
    wardName: 'K/E Ward – Andheri (East)',
    department: 'Roads & Infrastructure',
    employeeId: 'BMC/KE/2021/047',
    status: 'Available',
    assignedCount: 14,
    resolvedCount: 187,
    avgResolutionDays: 4.2,
    rating: 4.3,
    joinedAt: '2021-07-01T09:00:00Z',
  },
  {
    id: 'officer-002',
    name: 'Amol Desai',
    email: 'amol.desai@bmc.gov.in',
    phone: '+91 22 2416 7000',
    ward: 8,
    wardName: 'G/N Ward – Bandra (North)',
    department: 'Roads & Infrastructure',
    employeeId: 'BMC/GN/2019/023',
    status: 'Busy',
    assignedCount: 21,
    resolvedCount: 234,
    avgResolutionDays: 3.8,
    rating: 4.6,
    joinedAt: '2019-03-15T09:00:00Z',
  },
  {
    id: 'officer-003',
    name: 'Kavita Jadhav',
    email: 'kavita.jadhav@bmc.gov.in',
    phone: '+91 22 2416 8000',
    ward: 13,
    wardName: 'K/W Ward – Andheri (West)',
    department: 'Sanitation',
    employeeId: 'BMC/KW/2020/031',
    status: 'Available',
    assignedCount: 9,
    resolvedCount: 156,
    avgResolutionDays: 2.9,
    rating: 4.7,
    joinedAt: '2020-01-10T09:00:00Z',
  },
  {
    id: 'officer-004',
    name: 'Rahul Tiwari',
    email: 'rahul.tiwari@bmc.gov.in',
    phone: '+91 22 2416 9000',
    ward: 7,
    wardName: 'F/S Ward – Dharavi, Sion',
    department: 'Electrical',
    employeeId: 'BMC/FS/2018/015',
    status: 'On Leave',
    assignedCount: 0,
    resolvedCount: 312,
    avgResolutionDays: 3.1,
    rating: 4.4,
    joinedAt: '2018-06-01T09:00:00Z',
  },
  {
    id: 'officer-005',
    name: 'Sneha Mhatre',
    email: 'sneha.mhatre@bmc.gov.in',
    phone: '+91 22 2416 1000',
    ward: 25,
    wardName: 'RC Ward – Borivali (East)',
    department: 'Building & Permits',
    employeeId: 'BMC/RC/2022/058',
    status: 'Available',
    assignedCount: 6,
    resolvedCount: 89,
    avgResolutionDays: 5.1,
    rating: 3.9,
    joinedAt: '2022-09-01T09:00:00Z',
  },
  {
    id: 'officer-006',
    name: 'Vikram Salvi',
    email: 'vikram.salvi@bmc.gov.in',
    phone: '+91 22 2416 2000',
    ward: 16,
    wardName: 'M/W Ward – Chembur (West)',
    department: 'Sanitation',
    employeeId: 'BMC/MW/2017/009',
    status: 'Busy',
    assignedCount: 17,
    resolvedCount: 401,
    avgResolutionDays: 2.6,
    rating: 4.8,
    joinedAt: '2017-11-20T09:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif-001',
    type: 'status_update',
    title: 'Your complaint is now In Progress',
    body: 'Officer Amol Desai has started working on your pothole report near Bandra station.',
    complaintId: 'cmp-001',
    isRead: false,
    createdAt: makeDateAgo(0),
  },
  {
    id: 'notif-002',
    type: 'comment',
    title: 'New comment on your complaint',
    body: 'An officer added an update to your drainage complaint in Malad.',
    complaintId: 'cmp-004',
    isRead: false,
    createdAt: makeDateAgo(1),
  },
  {
    id: 'notif-003',
    type: 'resolved',
    title: 'Issue Resolved! 🎉',
    body: 'The streetlight issue at Dadar TT Circle has been marked as resolved.',
    complaintId: 'cmp-003',
    isRead: true,
    createdAt: makeDateAgo(8),
  },
  {
    id: 'notif-004',
    type: 'upvote',
    title: 'Your complaint gained 50+ upvotes',
    body: 'Your report about the drainage overflow in Malad now has 218 upvotes — community is paying attention!',
    complaintId: 'cmp-004',
    isRead: true,
    createdAt: makeDateAgo(2),
  },
  {
    id: 'notif-005',
    type: 'assigned',
    title: 'Complaint assigned to officer',
    body: 'Officer Kavita Jadhav has been assigned to the garbage issue at Lokhandwala.',
    complaintId: 'cmp-002',
    isRead: true,
    createdAt: makeDateAgo(4),
  },
];

export const MOCK_COMMENTS = {
  'cmp-001': [
    {
      id: 'comm-001',
      author: { id: 'user-001', name: 'Priya Nair', role: 'citizen' },
      text: 'I reported this 12 days ago. Two-wheelers have nearly fallen. Please expedite!',
      createdAt: makeDateAgo(12),
    },
    {
      id: 'comm-002',
      author: { id: 'officer-002', name: 'Amol Desai', role: 'officer' },
      text: 'Acknowledged. Materials for repair have been requisitioned. Work will begin by tomorrow morning (9 AM).',
      createdAt: makeDateAgo(3),
    },
    {
      id: 'comm-003',
      author: { id: 'user-009', name: 'Rajan Verma', role: 'citizen' },
      text: 'My bike tire burst because of this. Please make it urgent!',
      createdAt: makeDateAgo(2),
    },
  ],
};

export const MOCK_ANALYTICS = {
  dashboard: {
    totalComplaints: 14827,
    resolvedComplaints: 11204,
    resolutionRate: 75.6,
    avgResolutionDays: 3.7,
    activeOfficers: 84,
    highPriorityOpen: 127,
    citizenSatisfaction: 4.1,
    complaintsThisMonth: 1243,
    complaintsLastMonth: 1087,
    monthlyGrowth: 14.3,
  },
  byCategory: [
    { category: 'Pothole',        count: 4218, resolved: 3102, percentage: 28.4 },
    { category: 'Garbage',        count: 3547, resolved: 2891, percentage: 23.9 },
    { category: 'Drainage',       count: 2934, resolved: 1987, percentage: 19.8 },
    { category: 'Streetlight',    count: 2103, resolved: 1876, percentage: 14.2 },
    { category: 'Water Leakage',  count: 1456, resolved: 1148, percentage: 9.8  },
    { category: 'Other',          count:  569, resolved:  200, percentage: 3.8  },
  ],
  byWard: [
    { ward: 'K/E Ward', wardId: 12, total: 1247, resolved: 891, pending: 356, avgDays: 3.2, officers: 6, rate: 71.4 },
    { ward: 'G/N Ward', wardId: 8,  total: 1189, resolved: 967, pending: 222, avgDays: 2.8, officers: 5, rate: 81.3 },
    { ward: 'R/N Ward', wardId: 21, total: 1034, resolved: 712, pending: 322, avgDays: 4.1, officers: 4, rate: 68.9 },
    { ward: 'K/W Ward', wardId: 13, total:  987, resolved: 801, pending: 186, avgDays: 2.4, officers: 5, rate: 81.2 },
    { ward: 'P/N Ward', wardId: 18, total:  934, resolved: 623, pending: 311, avgDays: 4.8, officers: 3, rate: 66.7 },
    { ward: 'L Ward',   wardId: 14, total:  891, resolved: 734, pending: 157, avgDays: 3.0, officers: 4, rate: 82.4 },
    { ward: 'N Ward',   wardId: 17, total:  823, resolved: 612, pending: 211, avgDays: 3.9, officers: 3, rate: 74.4 },
    { ward: 'RS Ward',  wardId: 26, total:  798, resolved: 543, pending: 255, avgDays: 4.3, officers: 3, rate: 68.0 },
    { ward: 'H/E Ward', wardId: 10, total:  754, resolved: 687, pending:  67, avgDays: 2.1, officers: 4, rate: 91.1 },
    { ward: 'M/E Ward', wardId: 15, total:  712, resolved: 434, pending: 278, avgDays: 5.6, officers: 2, rate: 61.0 },
  ],
  trends: [
    { month: 'Apr', reported: 892,  resolved: 701, avgDays: 4.2 },
    { month: 'May', reported: 1034, resolved: 812, avgDays: 3.9 },
    { month: 'Jun', reported: 1421, resolved: 987, avgDays: 4.7 },
    { month: 'Jul', reported: 1876, resolved: 1234, avgDays: 5.1 },
    { month: 'Aug', reported: 2143, resolved: 1567, avgDays: 4.8 },
    { month: 'Sep', reported: 1987, resolved: 1645, avgDays: 3.7 },
  ],
  weatherCorrelation: [
    { month: 'Apr', complaints: 892,  avgAQI: 98  },
    { month: 'May', complaints: 1034, avgAQI: 112 },
    { month: 'Jun', complaints: 1421, avgAQI: 134 },
    { month: 'Jul', complaints: 1876, avgAQI: 158 },
    { month: 'Aug', complaints: 2143, avgAQI: 167 },
    { month: 'Sep', complaints: 1987, avgAQI: 141 },
  ],
};

export const MOCK_WEATHER = {
  aqi: 112,
  aqiCategory: 'Unhealthy for Sensitive Groups',
  condition: 'Partly Cloudy',
  temperature: 31,
  humidity: 74,
  description: 'Partly cloudy with high humidity. Monsoon conditions expected.',
  location: 'Mumbai, Maharashtra',
};

export const OFFICER_PERFORMANCE = {
  totalResolved: 187,
  avgResolutionDays: 4.2,
  lastMonthResolved: 23,
  prevMonthResolved: 19,
  trend: +21,
  satisfactionRatio: 4.3,
  weeklyResolved: [
    { week: 'Wk 1', resolved: 6 },
    { week: 'Wk 2', resolved: 8 },
    { week: 'Wk 3', resolved: 4 },
    { week: 'Wk 4', resolved: 7 },
    { week: 'Wk 5', resolved: 9 },
    { week: 'Wk 6', resolved: 5 },
    { week: 'Wk 7', resolved: 11 },
    { week: 'Wk 8', resolved: 7 },
  ],
  categoryBreakdown: [
    { name: 'Pothole',       value: 72, fill: '#16a34a' },
    { name: 'Drainage',      value: 45, fill: '#0ea5e9' },
    { name: 'Streetlight',   value: 38, fill: '#f59e0b' },
    { name: 'Garbage',       value: 21, fill: '#ea580c' },
    { name: 'Water Leakage', value: 11, fill: '#6366f1' },
  ],
};
